#!/bin/bash

#
# extracts setperm script from tarball
#


tarball=$1

if [ -z "$tarball" ]
then
	echo "Usage: $0 <tarball>"
	exit 1
fi


cat <<???
#!/bin/bash

#
# setperm script for package `cat PROJECT` version `cat VERSION`
#
# automatically generated by $0 on `date`
#

???

cat <<'???'

echo -n 'Setting permissions ...'
{ while `true`; do echo -n .; sleep .2; done } &


function setperm()
{
	owner=$1
	group=$2
	perm=$3
	file=$4

	chown $owner:$group $file  2> /dev/null
	chmod $perm $file          2> /dev/null
}


???


function perm2octal()
{
	local perm=${1:1}

	res=`echo $perm | sed 's/[^-]/1/g; s/-/0/g'`
	res=`echo "ibase=2; obase=8; $res" | bc`

	echo $res
}


tar tvfz $tarball | while read file
do
	perm=`echo $file | awk '{print $1}'`
	owner=`echo $file | awk '{print $2}'`
	name=`echo $file | awk '{print $6}'`

	# remove leading '.'
	name=${name:1}

	if [ -z "$name" ] || [ "$name" = '/' ]; then continue; fi

	octal=`perm2octal $perm`
	group=`cut -d'/' -f2 <<<$owner`
	owner=`cut -d'/' -f1 <<<$owner`

	echo setperm $owner $group $octal $name
done


cat <<'???'

kill $(jobs -p)
echo ' done'
???
