#!/usr/bin/perl -w


# snmp trap handler

# Put a line like the following in your snmptrapd.conf file:
#  traphandle TRAPOID|default $PATH$/traphandler

use IO::Socket;

$sock = new IO::Socket::INET (
	PeerAddr => '127.0.0.1',
	PeerPort => '6110',
	Proto => 'tcp');

die "Could not create socket: $!\n" unless $sock;

$tokenizer = ' @TRAPTKN@ ';

$buffer = "TRAP" . $tokenizer;

while(<STDIN>) {
	chomp;
	$buffer .= $tokenizer.$_;
}

print $sock $buffer;
close($sock);
