#!/bin/bash

RANDOM=$$

if [ $# -ne 4 ]; then
	echo "usage: $0 <target> <community> <hostname> <delay>"
	exit
fi

target="$1"
community="$2"
hostname="$3"
delay="$4"

while [ 1 ]
do
	status=$((RANDOM%3))
	output=`fortune -o | tr '\n' ' '`
	/usr/local/nagios/libexec/notifiche/send-host-trap $target@$community $hostname $status "$output" 1>&2 2>/dev/null &
	sleep $delay
done
